stages:
  - build

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - node_modules/
    - pnpm-lock.yaml

default:
  image: 'node:19-alpine3.16'
  before_script:
    - apk update && apk upgrade -U -a
    - apk add wget curl
    - >-
      wget -qO /bin/pnpm
      "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64"
      && chmod +x /bin/pnpm
    - pnpm config set store-dir .pnpm-store

build:
  stage: build
  tags:
    - docker
  cache:
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
      - node_modules/
      - pnpm-lock.yaml
    when: on_success
    policy: pull-push
  script:
    - pnpm i --no-frozen-lockfile
    - pnpm compile
  only:
    - branches
